# Generated by Django 5.2.7 on 2025-10-16 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('data_fato', models.DateField(help_text='Data do gasto (nota/comprovante)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.TextField(blank=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (não analisada)'), ('APROVADA', 'Aprovada (a reembolsar/paga)'), ('REPROVADA', 'Reprovada')], default='PENDENTE', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('observacao_admin', models.TextField(blank=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='despesas.centrodecusto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LoteReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_ref', models.CharField(help_text='Formato MM/AAAA (relatório/consulta)', max_length=7)),
                ('comprovante_reembolso', models.FileField(blank=True, null=True, upload_to='reembolsos/%Y/%m/')),
                ('pago_em', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_reembolso', to='despesas.centrodecusto')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_criados', to=settings.AUTH_USER_MODEL)),
                ('despesas', models.ManyToManyField(blank=True, related_name='lotes', to='despesas.despesa')),
            ],
            options={
                'verbose_name': 'Lote de Reembolso',
                'verbose_name_plural': 'Lotes de Reembolso',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AssociacaoCentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associacoes_cc', to=settings.AUTH_USER_MODEL)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associados', to='despesas.centrodecusto')),
            ],
            options={
                'verbose_name': 'Associação a Centro de Custo',
                'verbose_name_plural': 'Associações a Centros de Custo',
                'unique_together': {('usuario', 'centro')},
            },
        ),
    ]
