# Generated by Django 5.2.7 on 2025-10-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='reembolsos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='pago_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
