# Generated by Django 5.2.7 on 2025-10-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_despesa_comprovante_pagamento_despesa_pago_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='edit_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente (não analisada)'), ('APROVADA', 'Aprovada (paga)'), ('REPROVADA', 'Reprovada')], default='PENDENTE', max_length=12),
        ),
    ]
