# Generated by Django 5.2.7 on 2025-10-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0004_despesa_edit_count_alter_despesa_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="foi_avaliada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="despesa",
            name="primeira_analise_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="despesa",
            name="edit_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
