# Generated by Django 5.2.7 on 2025-10-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0006_usuarioperfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarioperfil",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=14, null=True, unique=True, verbose_name="CPF"
            ),
        ),
    ]
