# Generated by Django 5.2.7 on 2025-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0007_alter_usuarioperfil_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despesa",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente (não analisada)"),
                    ("PENDENTE_PAGTO", "Pendente de pagamento"),
                    ("APROVADA", "Aprovada (paga)"),
                    ("REPROVADA", "Reprovada"),
                ],
                default="PENDENTE",
                max_length=20,
            ),
        ),
    ]
