# Generated by Django 5.2.7 on 2025-11-24 19:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0008_alter_despesa_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "brasao",
                    models.ImageField(blank=True, null=True, upload_to="brasoes/"),
                ),
                (
                    "codigo_externo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Etapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("FECHAMENTO", "Fechamento"),
                            ("SIGA", "SIGA"),
                            ("SIOPS", "SIOPS"),
                            ("SIOPE", "SIOPE"),
                            ("SICONF", "SICONF"),
                            ("E-TCM", "E-TCM"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem de apresentação na tela (menor primeiro).",
                    ),
                ),
                ("obrigatoria_para_fila_siga", models.BooleanField(default=False)),
                ("obrigatoria_para_fila_etcm", models.BooleanField(default=False)),
                ("ativa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Etapa",
                "verbose_name_plural": "Etapas",
                "ordering": ["nivel", "ordem", "nome"],
                "unique_together": {("nivel", "nome")},
            },
        ),
        migrations.CreateModel(
            name="EtapaRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveIntegerField()),
                (
                    "mes",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NAO_INICIADO", "Não iniciado"),
                            ("EM_ANDAMENTO", "Em andamento"),
                            ("CONCLUIDO", "Concluído"),
                            ("PENDENTE", "Pendente"),
                        ],
                        default="NAO_INICIADO",
                        max_length=30,
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_etapas",
                        to="despesas.cliente",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros",
                        to="despesas.etapa",
                    ),
                ),
                (
                    "ultima_alteracao_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Etapa",
                "verbose_name_plural": "Registros de Etapas",
                "ordering": ["cliente", "-ano", "-mes", "etapa__ordem"],
                "unique_together": {("cliente", "etapa", "ano", "mes")},
            },
        ),
        migrations.CreateModel(
            name="EtapaHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_anterior",
                    models.CharField(
                        choices=[
                            ("NAO_INICIADO", "Não iniciado"),
                            ("EM_ANDAMENTO", "Em andamento"),
                            ("CONCLUIDO", "Concluído"),
                            ("PENDENTE", "Pendente"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(
                        choices=[
                            ("NAO_INICIADO", "Não iniciado"),
                            ("EM_ANDAMENTO", "Em andamento"),
                            ("CONCLUIDO", "Concluído"),
                            ("PENDENTE", "Pendente"),
                        ],
                        max_length=30,
                    ),
                ),
                ("observacao_anterior", models.TextField(blank=True)),
                ("observacao_nova", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="despesas.etaparegistro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Etapa",
                "verbose_name_plural": "Históricos de Etapas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="AssociacaoUsuarioCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associacoes_clientes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associacoes_usuarios",
                        to="despesas.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Associação Usuário-Cliente",
                "verbose_name_plural": "Associações Usuário-Cliente",
                "unique_together": {("usuario", "cliente")},
            },
        ),
        migrations.CreateModel(
            name="FilaAutomatica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex.: fila_siga, fila_etcm", max_length=80
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("FECHAMENTO", "Fechamento"),
                            ("SIGA", "SIGA"),
                            ("SIOPS", "SIOPS"),
                            ("SIOPE", "SIOPE"),
                            ("SICONF", "SICONF"),
                            ("E-TCM", "E-TCM"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "data_entrada",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("motivo", models.CharField(blank=True, max_length=255)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filas",
                        to="despesas.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fila automática",
                "verbose_name_plural": "Filas automáticas",
                "ordering": ["data_entrada"],
                "unique_together": {("nome", "cliente", "nivel")},
            },
        ),
    ]
