# Generated by Django 5.2.7 on 2025-12-02 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0011_pushmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("corpo", models.TextField()),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="URL a abrir quando clicar na notificação",
                        max_length=512,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("enviado", models.BooleanField(default=False)),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PushMessage",
        ),
    ]
