# Generated by Django 5.2.7 on 2025-12-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0012_notificationtemplate_delete_pushmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="NotificationTemplate",
        ),
    ]
