# Generated by Django 5.2.7 on 2025-12-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0013_notificationmessage_delete_notificationtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="etapa",
            name="obrigatoria_para_fila_siconf",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="etapa",
            name="obrigatoria_para_fila_siope",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="etapa",
            name="obrigatoria_para_fila_siops",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="filaautomatica",
            name="ordem_entrada",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Ordem sequencial de entrada na fila (1 = primeiro)",
                null=True,
            ),
        ),
    ]
