# Generated by Django 5.2.7 on 2025-12-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0014_etapa_obrigatoria_para_fila_siconf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarioperfil",
            name="acesso_etcm",
            field=models.BooleanField(default=False, verbose_name="Acesso E-TCM"),
        ),
        migrations.AddField(
            model_name="usuarioperfil",
            name="acesso_fechamento",
            field=models.BooleanField(default=False, verbose_name="Acesso Fechamento"),
        ),
        migrations.AddField(
            model_name="usuarioperfil",
            name="acesso_siconf",
            field=models.BooleanField(default=False, verbose_name="Acesso SICONFI"),
        ),
        migrations.AddField(
            model_name="usuarioperfil",
            name="acesso_siga",
            field=models.BooleanField(default=False, verbose_name="Acesso SIGA"),
        ),
        migrations.AddField(
            model_name="usuarioperfil",
            name="acesso_siope",
            field=models.BooleanField(default=False, verbose_name="Acesso SIOPE"),
        ),
        migrations.AddField(
            model_name="usuarioperfil",
            name="acesso_siops",
            field=models.BooleanField(default=False, verbose_name="Acesso SIOPS"),
        ),
    ]
