# Generated by Django 5.2.7 on 2025-12-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0015_usuarioperfil_acesso_etcm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rsvp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome completo"),
                ),
                (
                    "vai_ir",
                    models.BooleanField(default=False, verbose_name="Vai comparecer?"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
