# Generated by Django 5.2.7 on 2025-12-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0016_rsvp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etapa",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("FECHAMENTO", "FECHAMENTO"),
                    ("SIGA", "SIGA"),
                    ("SIOPS", "SIOPS"),
                    ("SIOPE", "SIOPE"),
                    ("SICONF", "SICONFI"),
                    ("E-TCM", "E-TCM"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="filaautomatica",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("FECHAMENTO", "FECHAMENTO"),
                    ("SIGA", "SIGA"),
                    ("SIOPS", "SIOPS"),
                    ("SIOPE", "SIOPE"),
                    ("SICONF", "SICONFI"),
                    ("E-TCM", "E-TCM"),
                ],
                max_length=30,
            ),
        ),
    ]
