# Generated by Django 5.2.7 on 2025-12-11 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0018_fcmtoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificacaoPush",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("mensagem", models.TextField()),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Link para abrir ao clicar (opcional)",
                        null=True,
                    ),
                ),
                ("enviado", models.BooleanField(default=False)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_envio", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario_alvo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Específico (Deixe vazio para enviar a todos)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nova Notificação Push",
                "verbose_name_plural": "Notificações Push",
            },
        ),
    ]
