# Generated by Django 5.2.7 on 2025-12-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0019_notificacaopush"),
    ]

    operations = [
        migrations.AddField(
            model_name="etapa",
            name="exige_anexo",
            field=models.BooleanField(
                default=False,
                help_text="Se marcado, o usuário deve anexar um arquivo para concluir esta etapa.",
                verbose_name="Exige Anexo (PDF/Img)",
            ),
        ),
        migrations.AddField(
            model_name="etaparegistro",
            name="arquivo_anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="comprovantes_etapas/%Y/%m/",
                verbose_name="Comprovante",
            ),
        ),
    ]
