# Generated by Django 5.2.7 on 2026-01-29 18:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0021_solicitacaoreabertura"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrefeituraSIOPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_prefeitura",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nome da Prefeitura"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug para URL")),
                (
                    "saudacao_nome",
                    models.CharField(
                        help_text="Ex: Excelentíssima Senhora Luís, Secretária de Saúde",
                        max_length=255,
                        verbose_name="Nome para Saudação",
                    ),
                ),
                (
                    "secretario_saude_default",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Secretário(a) de Saúde Padrão",
                    ),
                ),
                (
                    "logo_prefeitura",
                    models.ImageField(
                        help_text="Resolução recomendada: 200x100px",
                        upload_to="prefeituras/logos/",
                        verbose_name="Logo da Prefeitura",
                    ),
                ),
                (
                    "brasao_prefeitura",
                    models.ImageField(
                        blank=True,
                        help_text="Resolução recomendada: 150x150px",
                        null=True,
                        upload_to="prefeituras/brasoes/",
                        verbose_name="Brasão da Prefeitura",
                    ),
                ),
                (
                    "cor_primaria",
                    models.CharField(
                        default="#4a9fb5",
                        help_text="Ex: #4a9fb5",
                        max_length=7,
                        verbose_name="Cor Primária (Hex)",
                    ),
                ),
                (
                    "cor_secundaria",
                    models.CharField(
                        default="#3a8fa5",
                        max_length=7,
                        verbose_name="Cor Secundária (Hex)",
                    ),
                ),
                (
                    "endereco",
                    models.TextField(blank=True, verbose_name="Endereço da Prefeitura"),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Prefeitura Ativa"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prefeitura SIOPS",
                "verbose_name_plural": "Prefeituras SIOPS",
                "ordering": ["nome_prefeitura"],
            },
        ),
        migrations.CreateModel(
            name="QuestionarioSIOPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_siops",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número SIOPS"
                    ),
                ),
                (
                    "periodo_ref_inicio",
                    models.DateField(verbose_name="Período de Referência - Início"),
                ),
                (
                    "periodo_ref_fim",
                    models.DateField(verbose_name="Período de Referência - Fim"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "data_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Envio"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("enviado", "Enviado"),
                            ("revisado", "Revisado"),
                        ],
                        default="rascunho",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "prefeito_nome",
                    models.CharField(max_length=255, verbose_name="Nome do Prefeito"),
                ),
                (
                    "prefeito_endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereço"
                    ),
                ),
                (
                    "prefeito_telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "prefeito_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "secretario_nome",
                    models.CharField(
                        max_length=255, verbose_name="Nome do Secretário(a) de Saúde"
                    ),
                ),
                (
                    "secretario_endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereço"
                    ),
                ),
                (
                    "secretario_telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "secretario_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "conselho_data_criacao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Criação do Conselho",
                    ),
                ),
                (
                    "conselho_instrumento_criacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lei", "Lei"),
                            ("decreto", "Decreto"),
                            ("portaria", "Portaria"),
                            ("outro", "Outro"),
                        ],
                        max_length=255,
                        verbose_name="Instrumento de Criação",
                    ),
                ),
                (
                    "conselho_endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereço do Conselho"
                    ),
                ),
                (
                    "conselho_periodicidade_reunioes",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mensal", "Mensal"),
                            ("bimestral", "Bimestral"),
                            ("trimestral", "Trimestral"),
                            ("semestral", "Semestral"),
                            ("anual", "Anual"),
                            ("conforme_necessidade", "Conforme Necessidade"),
                        ],
                        max_length=50,
                        verbose_name="Periodicidade das Reuniões",
                    ),
                ),
                (
                    "conselho_presidente_nome",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome do Presidente"
                    ),
                ),
                (
                    "conselho_presidente_segmento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("governo", "Governo"),
                            ("usuario", "Usuário"),
                            ("trabalhador", "Trabalhador de Saúde"),
                            ("prestador", "Prestador"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                        verbose_name="Segmento do Presidente",
                    ),
                ),
                (
                    "conselho_presidente_endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereço"
                    ),
                ),
                (
                    "conselho_presidente_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "conselho_presidente_telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "responsavel_nome",
                    models.CharField(
                        max_length=255, verbose_name="Nome do Responsável"
                    ),
                ),
                (
                    "responsavel_email",
                    models.EmailField(
                        max_length=254, verbose_name="Email do Responsável"
                    ),
                ),
                (
                    "responsavel_telefone",
                    models.CharField(
                        max_length=20, verbose_name="Telefone do Responsável"
                    ),
                ),
                (
                    "fundo_data_criacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Criação do Fundo"
                    ),
                ),
                (
                    "fundo_instrumento_criacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lei", "Lei"),
                            ("decreto", "Decreto"),
                            ("portaria", "Portaria"),
                            ("outro", "Outro"),
                        ],
                        max_length=255,
                        verbose_name="Instrumento de Criação",
                    ),
                ),
                (
                    "fundo_cnpj_tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prefeitura", "Prefeitura"),
                            ("fundacao", "Fundação"),
                            ("secretaria_saude", "Secretaria de Saúde"),
                            ("fundo_saude", "Fundo de Saúde"),
                            ("outra_secretaria", "Outra Secretaria"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                        verbose_name="CNPJ Utilizado",
                    ),
                ),
                (
                    "fundo_cnpj",
                    models.CharField(
                        blank=True, max_length=18, verbose_name="Número do CNPJ"
                    ),
                ),
                (
                    "fundo_endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereço do Fundo"
                    ),
                ),
                (
                    "fundo_responsavel_nome",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome do Responsável"
                    ),
                ),
                (
                    "fundo_responsavel_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "fundo_responsavel_telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "fundo_banco",
                    models.CharField(blank=True, max_length=50, verbose_name="Banco"),
                ),
                (
                    "fundo_agencia",
                    models.CharField(blank=True, max_length=20, verbose_name="Agência"),
                ),
                (
                    "fundo_conta",
                    models.CharField(blank=True, max_length=50, verbose_name="Conta"),
                ),
                (
                    "fundo_pleno_funcionamento",
                    models.BooleanField(
                        default=False, verbose_name="Fundo em pleno funcionamento?"
                    ),
                ),
                (
                    "fundo_gestor_nome",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome do Gestor"
                    ),
                ),
                (
                    "fundo_administracao_local",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("secretaria_saude", "Secretaria de Saúde"),
                            ("secretaria_fazenda", "Secretaria da Fazenda"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                        verbose_name="Onde está a administração?",
                    ),
                ),
                (
                    "fundo_recursos_proprios_aplicados",
                    models.BooleanField(
                        default=False,
                        verbose_name="Recursos próprios aplicados através do Fundo?",
                    ),
                ),
                (
                    "fundo_recursos_proprios_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Percentual de Recursos Próprios (%)",
                    ),
                ),
                (
                    "fundo_recursos_sus_aplicados",
                    models.BooleanField(
                        default=False,
                        verbose_name="Recursos SUS aplicados através do Fundo?",
                    ),
                ),
                (
                    "fundo_recursos_sus_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Percentual de Recursos SUS (%)",
                    ),
                ),
                (
                    "conselho_acompanha_fundo",
                    models.BooleanField(
                        default=False, verbose_name="Acompanha e fiscaliza o Fundo?"
                    ),
                ),
                (
                    "conselho_analisa_plano_saude",
                    models.BooleanField(
                        default=False,
                        verbose_name="Analisa e emite parecer ao Plano de Saúde?",
                    ),
                ),
                (
                    "conselho_analisa_ppa",
                    models.BooleanField(
                        default=False,
                        verbose_name="Analisa e emite parecer à Proposta de PPA?",
                    ),
                ),
                (
                    "conselho_delibera_programacao",
                    models.BooleanField(
                        default=False, verbose_name="Delibera a Programação Anual?"
                    ),
                ),
                (
                    "conselho_delibera_loa",
                    models.BooleanField(
                        default=False, verbose_name="Delibera sobre a Proposta da LOA?"
                    ),
                ),
                (
                    "conselho_delibera_gestao",
                    models.BooleanField(
                        default=False, verbose_name="Delibera o Relatório de Gestão?"
                    ),
                ),
                (
                    "conselho_analisa_gestao",
                    models.BooleanField(
                        default=False,
                        verbose_name="Analisa e emite parecer no Relatório de Gestão?",
                    ),
                ),
                (
                    "conselho_analisa_contas",
                    models.BooleanField(
                        default=False,
                        verbose_name="Analisa e emite parecer nas contas de cada quadrimestre?",
                    ),
                ),
                (
                    "consorcio_nome",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome do Consórcio"
                    ),
                ),
                (
                    "consorcio_cnpj",
                    models.CharField(
                        blank=True, max_length=18, verbose_name="CNPJ do Consórcio"
                    ),
                ),
                (
                    "consorcio_responsavel",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Responsável"
                    ),
                ),
                (
                    "consorcio_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "consorcio_telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "prefeitura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionarios",
                        to="despesas.prefeiturasiops",
                        verbose_name="Prefeitura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questionário SIOPS",
                "verbose_name_plural": "Questionários SIOPS",
                "ordering": ["-data_atualizacao"],
            },
        ),
        migrations.CreateModel(
            name="MembrosConselho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "representacao",
                    models.CharField(
                        max_length=255, verbose_name="Representação/Segmento"
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereço"
                    ),
                ),
                (
                    "cep",
                    models.CharField(blank=True, max_length=10, verbose_name="CEP"),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "questionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros_conselho",
                        to="despesas.questionariosiops",
                        verbose_name="Questionário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro do Conselho",
                "verbose_name_plural": "Membros do Conselho",
                "ordering": ["nome"],
            },
        ),
    ]
