# Generated by Django 5.2.7 on 2026-01-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0022_prefeiturasiops_questionariosiops_membrosconselho"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionariosiops",
            name="prefeitura",
        ),
        migrations.DeleteModel(
            name="MembrosConselho",
        ),
        migrations.DeleteModel(
            name="PrefeituraSIOPS",
        ),
        migrations.DeleteModel(
            name="QuestionarioSIOPS",
        ),
    ]
