# Generated by Django 5.2.7 on 2026-01-30 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0023_remove_questionariosiops_prefeitura_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prefeitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: Prefeitura Municipal de Salvador",
                        max_length=200,
                        verbose_name="Nome da Prefeitura",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único para o link (ex: salvador)",
                        unique=True,
                        verbose_name="Identificador na URL",
                    ),
                ),
                (
                    "brasao",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brasoes/",
                        verbose_name="Brasão/Logo",
                    ),
                ),
                (
                    "nome_responsavel_recepcao",
                    models.CharField(
                        help_text="Nome que aparecerá no 'Olá, [Nome]'. Ex: Conmac Gestão",
                        max_length=150,
                        verbose_name="Nome do Responsável na Saudação",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para bloquear o acesso a este formulário imediatamente.",
                        verbose_name="Formulário Ativo?",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prefeitura / Entidade",
                "verbose_name_plural": "Prefeituras / Entidades",
            },
        ),
        migrations.CreateModel(
            name="QuestionarioSIOPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Envio"
                    ),
                ),
                (
                    "prefeito_nome",
                    models.CharField(max_length=200, verbose_name="Nome do Prefeito"),
                ),
                (
                    "prefeito_endereco",
                    models.CharField(
                        max_length=255, verbose_name="Endereço do Prefeito"
                    ),
                ),
                (
                    "prefeito_telefone",
                    models.CharField(
                        max_length=20, verbose_name="Telefone do Prefeito"
                    ),
                ),
                (
                    "prefeito_email",
                    models.EmailField(
                        max_length=254, verbose_name="E-mail do Prefeito"
                    ),
                ),
                (
                    "secretario_nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome do Secretário de Saúde"
                    ),
                ),
                (
                    "secretario_endereco",
                    models.CharField(
                        max_length=255, verbose_name="Endereço do Secretário"
                    ),
                ),
                (
                    "secretario_telefone",
                    models.CharField(
                        max_length=20, verbose_name="Telefone do Secretário"
                    ),
                ),
                (
                    "secretario_email",
                    models.EmailField(
                        max_length=254, verbose_name="E-mail do Secretário"
                    ),
                ),
                (
                    "conselho_data_criacao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Criação do Conselho [cite: 16]",
                    ),
                ),
                (
                    "conselho_instrumento",
                    models.CharField(
                        help_text="Lei, Decreto, Portaria ou Outro [cite: 17]",
                        max_length=200,
                        verbose_name="Instrumento de Criação",
                    ),
                ),
                (
                    "conselho_endereco",
                    models.CharField(
                        max_length=255, verbose_name="Endereço do Conselho"
                    ),
                ),
                (
                    "conselho_periodicidade",
                    models.CharField(
                        max_length=100, verbose_name="Periodicidade das Reuniões"
                    ),
                ),
                (
                    "presidente_nome",
                    models.CharField(
                        max_length=200,
                        verbose_name="Nome do Presidente do Conselho [cite: 23]",
                    ),
                ),
                (
                    "presidente_segmento",
                    models.CharField(
                        choices=[
                            ("GOV", "Governo"),
                            ("USU", "Usuário"),
                            ("TRAB", "Trabalhador de Saúde"),
                            ("PRES", "Prestador de Serviço"),
                        ],
                        max_length=5,
                        verbose_name="Segmento do Presidente [cite: 24, 43]",
                    ),
                ),
                (
                    "presidente_endereco",
                    models.CharField(
                        max_length=255, verbose_name="Endereço do Presidente"
                    ),
                ),
                (
                    "presidente_email",
                    models.EmailField(
                        max_length=254, verbose_name="E-mail do Presidente"
                    ),
                ),
                (
                    "presidente_telefone",
                    models.CharField(
                        max_length=20, verbose_name="Telefone do Presidente"
                    ),
                ),
                (
                    "responsavel_info_nome",
                    models.CharField(
                        max_length=200, verbose_name="Responsável pelas Informações"
                    ),
                ),
                (
                    "responsavel_info_email",
                    models.EmailField(
                        max_length=254, verbose_name="E-mail do Responsável Info"
                    ),
                ),
                (
                    "responsavel_info_telefone",
                    models.CharField(
                        max_length=20, verbose_name="Telefone do Responsável Info"
                    ),
                ),
                (
                    "fiscaliza_fundo",
                    models.BooleanField(
                        default=False,
                        verbose_name="Acompanha e fiscaliza o Fundo em caráter permanente?",
                    ),
                ),
                (
                    "parecer_plano",
                    models.BooleanField(
                        default=False, verbose_name="Emite Parecer ao Plano de Saúde?"
                    ),
                ),
                (
                    "parecer_ppa",
                    models.BooleanField(
                        default=False, verbose_name="Emite Parecer à Proposta de PPA?"
                    ),
                ),
                (
                    "delibera_programacao",
                    models.BooleanField(
                        default=False, verbose_name="Delibera a Programação Anual?"
                    ),
                ),
                (
                    "delibera_loa",
                    models.BooleanField(
                        default=False, verbose_name="Delibera sobre a Proposta da LOA?"
                    ),
                ),
                (
                    "delibera_relatorio_gestao",
                    models.BooleanField(
                        default=False, verbose_name="Delibera o Relatório de Gestão?"
                    ),
                ),
                (
                    "parecer_relatorio_gestao",
                    models.BooleanField(
                        default=False,
                        verbose_name="Emite Parecer no Relatório de Gestão (Anual)?",
                    ),
                ),
                (
                    "parecer_contas_quadrimestre",
                    models.BooleanField(
                        default=False,
                        verbose_name="Emite Parecer nas contas de cada quadrimestre?",
                    ),
                ),
                (
                    "fundo_cnpj",
                    models.CharField(
                        max_length=20, verbose_name="CNPJ Utilizado [cite: 99]"
                    ),
                ),
                (
                    "fundo_tipo_gestao",
                    models.CharField(
                        choices=[
                            ("PREF", "Prefeitura"),
                            ("FUNDO", "Fundo de Saúde"),
                            ("FUNDACAO", "Fundação"),
                            ("SEC", "Sec. de Saúde"),
                            ("OUTRA_SEC", "Outra Secretaria"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=15,
                        verbose_name="Gestão do CNPJ [cite: 88]",
                    ),
                ),
                (
                    "fundo_endereco",
                    models.CharField(max_length=255, verbose_name="Endereço do Fundo"),
                ),
                (
                    "fundo_responsavel_nome",
                    models.CharField(
                        max_length=200, verbose_name="Responsável pelo Fundo"
                    ),
                ),
                (
                    "fundo_responsavel_email",
                    models.EmailField(
                        max_length=254, verbose_name="E-mail Responsável Fundo"
                    ),
                ),
                (
                    "fundo_responsavel_telefone",
                    models.CharField(
                        max_length=20, verbose_name="Telefone Responsável Fundo"
                    ),
                ),
                ("banco_nome", models.CharField(max_length=100, verbose_name="Banco")),
                (
                    "banco_agencia",
                    models.CharField(max_length=20, verbose_name="Agência"),
                ),
                ("banco_conta", models.CharField(max_length=20, verbose_name="Conta")),
                (
                    "fundo_pleno_funcionamento",
                    models.BooleanField(
                        default=True,
                        verbose_name="O Fundo está em pleno funcionamento?",
                    ),
                ),
                (
                    "fundo_nome_gestor",
                    models.CharField(
                        max_length=200, verbose_name="Nome do Gestor do Fundo"
                    ),
                ),
                (
                    "fundo_local_administracao",
                    models.CharField(
                        choices=[
                            ("SAUDE", "Secretaria de Saúde"),
                            ("FAZENDA", "Secretaria da Fazenda"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Onde está a administração do Fundo?",
                    ),
                ),
                (
                    "recursos_proprios_aplicados",
                    models.BooleanField(
                        default=False,
                        verbose_name="Recursos próprios são aplicados através do FUNDO?",
                    ),
                ),
                (
                    "recursos_proprios_percentual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Percentual Recursos Próprios (%)",
                    ),
                ),
                (
                    "recursos_sus_aplicados",
                    models.BooleanField(
                        default=False,
                        verbose_name="Recursos do SUS são aplicados através do Fundo?",
                    ),
                ),
                (
                    "recursos_sus_percentual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Percentual Recursos SUS (%)",
                    ),
                ),
                (
                    "possui_consorcio",
                    models.BooleanField(
                        default=False,
                        verbose_name="O município participa de Consórcio de Saúde?",
                    ),
                ),
                (
                    "consorcio_nome",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome do Consórcio",
                    ),
                ),
                (
                    "consorcio_cnpj",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="CNPJ do Consórcio",
                    ),
                ),
                (
                    "consorcio_responsavel",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Responsável do Consórcio",
                    ),
                ),
                (
                    "consorcio_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="E-mail do Consórcio",
                    ),
                ),
                (
                    "consorcio_telefone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telefone do Consórcio",
                    ),
                ),
                (
                    "prefeitura",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionario",
                        to="despesas.prefeitura",
                        verbose_name="Prefeitura Vinculada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questionário Respondido",
                "verbose_name_plural": "Questionários Respondidos",
            },
        ),
    ]
