# Generated by Django 5.2.7 on 2026-02-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0024_prefeitura_questionariosiops"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoNivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("FECHAMENTO", "FECHAMENTO"),
                            ("SIGA", "SIGA"),
                            ("SIOPS", "SIOPS"),
                            ("SIOPE", "SIOPE"),
                            ("SICONF", "SICONFI"),
                            ("E-TCM", "E-TCM"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "liberar_preenchimento",
                    models.BooleanField(
                        default=False, verbose_name="Liberar para preenchimento?"
                    ),
                ),
            ],
        ),
    ]
