# Generated by Django 5.2.7 on 2026-02-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0025_configuracaonivel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracaonivel",
            options={
                "ordering": ["nivel"],
                "verbose_name": "Configuração de Nível",
                "verbose_name_plural": "Configurações de Níveis",
            },
        ),
        migrations.AddField(
            model_name="configuracaonivel",
            name="clientes_liberados",
            field=models.ManyToManyField(
                blank=True,
                help_text="Se vazio e 'Liberar' estiver marcado, libera para TODOS. Se tiver clientes, libera APENAS os selecionados.",
                related_name="configuracoes_nivel_liberadas",
                to="despesas.cliente",
                verbose_name="Clientes com acesso específico",
            ),
        ),
    ]
