# Generated by Django 5.2.7 on 2026-02-12 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0026_alter_configuracaonivel_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "omie_cod_ctr",
                    models.BigIntegerField(
                        unique=True, verbose_name="Cód. Contrato Omie (nCodCtr)"
                    ),
                ),
                (
                    "omie_num_ctr",
                    models.CharField(max_length=60, verbose_name="Número do Contrato"),
                ),
                (
                    "cliente_id_omie",
                    models.BigIntegerField(verbose_name="ID Cliente Omie (nCodCli)"),
                ),
                (
                    "cliente_nome",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome do Cliente",
                    ),
                ),
                (
                    "valor_mensal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Mensal (nValTotMes)",
                    ),
                ),
                ("data_vigencia_inicial", models.DateField(blank=True, null=True)),
                ("data_vigencia_final", models.DateField(blank=True, null=True)),
                (
                    "status_omie",
                    models.CharField(default="Desconhecido", max_length=20),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contrato Omie",
                "verbose_name_plural": "Contratos Omie",
            },
        ),
        migrations.CreateModel(
            name="ServicoExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        max_length=255, verbose_name="Descrição do Serviço"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                ("data_servico", models.DateField(verbose_name="Data do Serviço")),
                (
                    "omie_os_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="ID OS Omie"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servicos_extras",
                        to="despesas.contrato",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço Extra",
                "verbose_name_plural": "Serviços Extras",
            },
        ),
    ]
