# Generated by Django 5.2.7 on 2026-02-23 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0027_contrato_servicoextra"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CartaoCorporativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "habilitado",
                    models.BooleanField(
                        default=False,
                        help_text="Se desmarcado, o analista não verá informações de limite ou saldo.",
                        verbose_name="Habilitar Cartão Empresarial",
                    ),
                ),
                (
                    "limite",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000.0,
                        max_digits=10,
                        verbose_name="Limite Padrão",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartao_corporativo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Analista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartão Empresarial",
                "verbose_name_plural": "Cartões Empresariais",
            },
        ),
    ]
