# Generated by Django 5.2.7 on 2026-02-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0028_cartaocorporativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartaocorporativo",
            name="excedente",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Acúmulo de saldo negativo perdoado/reembolsado nas recargas.",
                max_digits=12,
                verbose_name="Excedente (Gasto do Bolso)",
            ),
        ),
        migrations.AddField(
            model_name="cartaocorporativo",
            name="offset_saldo",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor matemático interno para equilibrar recargas.",
                max_digits=12,
                verbose_name="Offset de Saldo (Recargas)",
            ),
        ),
        migrations.AlterField(
            model_name="cartaocorporativo",
            name="habilitado",
            field=models.BooleanField(
                default=False, verbose_name="Habilitar Cartão Empresarial"
            ),
        ),
    ]
