# Generated by Django 5.2.7 on 2026-02-23 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0029_cartaocorporativo_excedente_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartaocorporativo",
            name="offset_saldo",
        ),
        migrations.AddField(
            model_name="cartaocorporativo",
            name="saldo_atual",
            field=models.DecimalField(
                decimal_places=2,
                default=1000.0,
                max_digits=12,
                verbose_name="Saldo Disponível",
            ),
        ),
        migrations.AlterField(
            model_name="cartaocorporativo",
            name="excedente",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Excedente (Gasto do Bolso)",
            ),
        ),
        migrations.CreateModel(
            name="TransacaoCartao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_debitado_saldo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "valor_jogado_excedente",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "despesa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacao_cartao",
                        to="despesas.despesa",
                    ),
                ),
            ],
        ),
    ]
