# Generated by Django 5.2.7 on 2026-03-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0030_remove_cartaocorporativo_offset_saldo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarioperfil",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Funcionário Ativo"),
        ),
        migrations.AddField(
            model_name="usuarioperfil",
            name="data_admissao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Admissão"
            ),
        ),
        migrations.AddField(
            model_name="usuarioperfil",
            name="salario_base",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Salário Base",
            ),
        ),
    ]
