# Generated by Django 5.2.7 on 2026-03-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0031_usuarioperfil_ativo_usuarioperfil_data_admissao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarioperfil",
            name="irrf_manual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="IRRF Manual",
            ),
        ),
    ]
