# Generated by Django 5.2.7 on 2026-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0032_usuarioperfil_irrf_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarioperfil",
            name="cargo",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Cargo"
            ),
        ),
        migrations.AddField(
            model_name="usuarioperfil",
            name="local_trabalho",
            field=models.CharField(
                blank=True,
                choices=[("nucleo", "Núcleo"), ("externo", "Externo")],
                max_length=20,
                null=True,
                verbose_name="Local de Trabalho",
            ),
        ),
    ]
