# Generated by Django 5.2.7 on 2026-03-04 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0033_usuarioperfil_cargo_usuarioperfil_local_trabalho"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "omie_nfse_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="ID NFS-e Omie (nNFSeInt)"
                    ),
                ),
                (
                    "numero_nfse",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Número NFS-e",
                    ),
                ),
                (
                    "omie_os_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="ID OS Omie"
                    ),
                ),
                (
                    "cliente_nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição do Serviço"
                    ),
                ),
                (
                    "valor_bruto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_iss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "competencia_mes",
                    models.PositiveSmallIntegerField(verbose_name="Mês"),
                ),
                (
                    "competencia_ano",
                    models.PositiveSmallIntegerField(verbose_name="Ano"),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Emissão"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("emitida", "Emitida"),
                            ("cancelada", "Cancelada"),
                            ("pendente", "Pendente"),
                        ],
                        default="emitida",
                        max_length=20,
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_fiscais",
                        to="despesas.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Fiscal (NFS-e)",
                "verbose_name_plural": "Notas Fiscais (NFS-e)",
                "ordering": ["-competencia_ano", "-competencia_mes", "-data_emissao"],
            },
        ),
        migrations.CreateModel(
            name="RecebimentoNota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confirmado",
                    models.BooleanField(default=False, verbose_name="Recebido?"),
                ),
                (
                    "valor_recebido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Deixe em branco para usar o valor líquido da nota.",
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Efetivamente Recebido",
                    ),
                ),
                (
                    "data_recebimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Recebimento"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                ("registrado_em", models.DateTimeField(auto_now=True)),
                (
                    "nota",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmacao",
                        to="despesas.notafiscal",
                        verbose_name="Nota Fiscal",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Confirmação de Recebimento",
                "verbose_name_plural": "Confirmações de Recebimento",
            },
        ),
    ]
