# Generated by Django 5.2.7 on 2026-03-05 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0034_notafiscal_recebimentonota"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="municipio",
            field=models.CharField(
                blank=True,
                help_text="Município do cliente/contrato. Usado para agrupar NFS-e no relatório.",
                max_length=120,
                null=True,
                verbose_name="Município",
            ),
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="inativada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="inativada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notas_inativadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Inativada por",
            ),
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="motivo_inativacao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motivo da inativação"
            ),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="data_emissao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="omie_nfse_id",
            field=models.BigIntegerField(
                unique=True, verbose_name="ID NFS-e Omie (nCodNF)"
            ),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="status",
            field=models.CharField(
                choices=[
                    ("emitida", "Emitida"),
                    ("cancelada", "Cancelada"),
                    ("inativa", "Inativa"),
                ],
                default="emitida",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recebimentonota",
            name="confirmado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="recebimentonota",
            name="data_recebimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recebimentonota",
            name="nota",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirmacao",
                to="despesas.notafiscal",
            ),
        ),
        migrations.AlterField(
            model_name="recebimentonota",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recebimentonota",
            name="registrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recebimentonota",
            name="valor_recebido",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
