# Generated by Django 5.2.7 on 2026-03-05 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0035_contrato_municipio_notafiscal_inativada_em_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="tipo_entidade",
            field=models.CharField(
                blank=True,
                choices=[("municipio", "Município"), ("camara", "Câmara Municipal")],
                help_text="Município = Prefeitura/Órgão municipal. Câmara = Câmara Municipal.",
                max_length=20,
                null=True,
                verbose_name="Tipo de Entidade",
            ),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="competencia_ano",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="competencia_mes",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="inativada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notas_inativadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="motivo_inativacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="omie_nfse_id",
            field=models.BigIntegerField(unique=True, verbose_name="ID NFS-e Omie"),
        ),
    ]
