# Generated by Django 5.2.7 on 2026-03-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0036_contrato_tipo_entidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="tipo_entidade",
            field=models.CharField(
                blank=True,
                choices=[("prefeitura", "Prefeitura"), ("camara", "Câmara Municipal")],
                help_text="Município = Prefeitura/Órgão municipal. Câmara = Câmara Municipal.",
                max_length=20,
                null=True,
                verbose_name="Tipo de Entidade",
            ),
        ),
    ]
