# Generated by Django 5.2.7 on 2026-03-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0037_alter_contrato_tipo_entidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="tipo_entidade",
            field=models.CharField(
                blank=True,
                choices=[("municipio", "Prefeitura"), ("camara", "Câmara Municipal")],
                help_text="Município = Prefeitura/Órgão municipal. Câmara = Câmara Municipal.",
                max_length=20,
                null=True,
                verbose_name="Tipo de Entidade",
            ),
        ),
    ]
