# Generated by Django 5.2.7 on 2026-03-10 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0038_alter_contrato_tipo_entidade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "declaracao_simples",
                                "Declaração de Optante pelo Simples Nacional",
                            ),
                            ("planilha_custos", "Planilha de Custos"),
                            ("relatorio_atividades", "Relatório de Atividades"),
                        ],
                        max_length=40,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "tipo_entidade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("municipio", "Prefeitura Municipal"),
                            ("camara", "Câmara Municipal"),
                            ("", "Todas as entidades"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Entidade",
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True,
                        help_text="Deixe em branco para valer para todos os municípios.",
                        max_length=120,
                        verbose_name="Município específico",
                    ),
                ),
                (
                    "arquivo_base",
                    models.FileField(
                        upload_to="docs_modelo/base/",
                        verbose_name="Arquivo Base (PDF original)",
                    ),
                ),
                (
                    "texto_data_original",
                    models.CharField(
                        help_text='Texto exato que aparece no PDF base e será substituído. Ex: "Salvador - BA, 20 de janeiro de 2026"',
                        max_length=300,
                        verbose_name="Texto da data no PDF base",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="Descrição / Instruções"),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docs_modelo_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Modelo",
                "verbose_name_plural": "Documentos Modelo",
                "ordering": ["tipo_entidade", "tipo"],
                "unique_together": {("tipo", "tipo_entidade", "municipio")},
            },
        ),
        migrations.CreateModel(
            name="DocumentoPadrao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("fgts", "Certidão de Regularidade do FGTS"),
                            ("estadual", "Certidão Negativa Estadual"),
                            ("federal", "Certidão Negativa Federal"),
                            ("municipal", "Certidão Negativa Municipal"),
                            ("trabalhista", "Certidão Negativa Trabalhista"),
                            ("simples", "Comprovação do Simples Nacional"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="docs_padrao/", verbose_name="Arquivo PDF"
                    ),
                ),
                ("data_validade", models.DateField(verbose_name="Validade")),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docs_padrao_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Padrão",
                "verbose_name_plural": "Documentos Padrão",
                "ordering": ["tipo"],
            },
        ),
        migrations.CreateModel(
            name="NotaFiscalPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="docs_nfse/", verbose_name="PDF da NFS-e"
                    ),
                ),
                (
                    "url_omie",
                    models.URLField(blank=True, verbose_name="URL original Omie"),
                ),
                ("baixado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "baixado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfse_pdfs_baixados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nota",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_local",
                        to="despesas.notafiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF de NFS-e",
                "verbose_name_plural": "PDFs de NFS-e",
            },
        ),
        migrations.CreateModel(
            name="ContratoEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "nome_contato",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Nome do Contato"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(default=False, verbose_name="Principal"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="despesas.contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-mail do Contrato",
                "verbose_name_plural": "E-mails dos Contratos",
                "ordering": ["-principal", "email"],
                "unique_together": {("contrato", "email")},
            },
        ),
        migrations.CreateModel(
            name="DocumentoModeloGerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.PositiveSmallIntegerField(verbose_name="Mês")),
                ("ano", models.PositiveSmallIntegerField(verbose_name="Ano")),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="docs_modelo/gerados/", verbose_name="Arquivo Gerado"
                    ),
                ),
                (
                    "texto_data_novo",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Texto da data substituído",
                    ),
                ),
                ("gerado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docs_modelo_gerados",
                        to="despesas.contrato",
                    ),
                ),
                (
                    "gerado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docs_gerados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gerados",
                        to="despesas.documentomodelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Modelo Gerado",
                "verbose_name_plural": "Documentos Modelo Gerados",
                "ordering": ["-ano", "-mes"],
                "unique_together": {("modelo", "contrato", "mes", "ano")},
            },
        ),
        migrations.CreateModel(
            name="EnvioMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.PositiveSmallIntegerField(verbose_name="Mês")),
                ("ano", models.PositiveSmallIntegerField(verbose_name="Ano")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente de Envio"),
                            ("enviado", "Enviado"),
                            ("externo", "Envio Externo"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios_mensais",
                        to="despesas.contrato",
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envios_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nota_fiscal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envios",
                        to="despesas.notafiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envio Mensal",
                "verbose_name_plural": "Envios Mensais",
                "ordering": ["-ano", "-mes", "contrato__cliente_nome"],
                "unique_together": {("contrato", "mes", "ano")},
            },
        ),
    ]
