# Generated by Django 5.2.7 on 2026-03-10 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0039_documentomodelo_documentopadrao_notafiscalpdf_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentomodelo",
            options={
                "ordering": ["contrato", "tipo"],
                "verbose_name": "Documento Modelo",
                "verbose_name_plural": "Documentos Modelo",
            },
        ),
        migrations.AlterUniqueTogether(
            name="documentomodelo",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="documentomodelogerado",
            unique_together={("modelo", "mes", "ano")},
        ),
        migrations.AddField(
            model_name="documentomodelo",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="documentomodelo",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="docs_modelo",
                to="despesas.contrato",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="documentomodelo",
            name="criado_em",
            field=models.DateTimeField(default="00/00/0000"),
        ),
        migrations.AddField(
            model_name="documentomodelo",
            name="nome_personalizado",
            field=models.CharField(
                blank=True,
                help_text='Opcional. Sobrepe o tipo na exibicao. Ex: "Planilha de Custos — CM Apora"',
                max_length=120,
                verbose_name="Nome personalizado",
            ),
        ),
        migrations.AddField(
            model_name="enviomensal",
            name="primeiro_envio_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Primeiro envio em"
            ),
        ),
        migrations.AlterField(
            model_name="documentomodelo",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Observacoes"),
        ),
        migrations.AlterField(
            model_name="documentomodelo",
            name="texto_data_original",
            field=models.CharField(
                help_text='Texto exato que aparece no PDF e sera substituido mensalmente. Ex: "Oliveira dos Brejinhos - BA, 20 de janeiro de 2026"',
                max_length=300,
                verbose_name="Texto de data no PDF base",
            ),
        ),
        migrations.AlterField(
            model_name="documentomodelo",
            name="tipo",
            field=models.CharField(
                choices=[
                    (
                        "declaracao_simples",
                        "Declaracao de Optante pelo Simples Nacional",
                    ),
                    ("planilha_custos", "Planilha de Custos"),
                    ("relatorio_atividades", "Relatorio de Atividades"),
                    ("outro", "Outro"),
                ],
                max_length=40,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="documentomodelogerado",
            name="mes",
            field=models.PositiveSmallIntegerField(verbose_name="Mes"),
        ),
        migrations.AlterField(
            model_name="documentomodelogerado",
            name="texto_data_novo",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Texto de data substituido"
            ),
        ),
        migrations.RemoveField(
            model_name="documentomodelo",
            name="municipio",
        ),
        migrations.RemoveField(
            model_name="documentomodelo",
            name="tipo_entidade",
        ),
        migrations.RemoveField(
            model_name="documentomodelogerado",
            name="contrato",
        ),
    ]
