# Generated by Django 5.2.7 on 2026-03-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0040_alter_documentomodelo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentomodelo",
            options={
                "ordering": ["tipo_entidade", "tipo"],
                "verbose_name": "Documento Modelo",
                "verbose_name_plural": "Documentos Modelo",
            },
        ),
        migrations.AlterUniqueTogether(
            name="documentomodelogerado",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="documentomodelo",
            unique_together={("tipo", "tipo_entidade", "municipio")},
        ),
        migrations.AddField(
            model_name="documentomodelo",
            name="municipio",
            field=models.CharField(
                blank=True,
                help_text="Deixe em branco para valer para todos os municípios.",
                max_length=120,
                verbose_name="Município específico",
            ),
        ),
        migrations.AddField(
            model_name="documentomodelo",
            name="tipo_entidade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("municipio", "Prefeitura Municipal"),
                    ("camara", "Câmara Municipal"),
                    ("", "Todas as entidades"),
                ],
                default="",
                max_length=20,
                verbose_name="Entidade",
            ),
        ),
        migrations.AddField(
            model_name="documentomodelogerado",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="docs_modelo_gerados",
                to="despesas.contrato",
            ),
        ),
        migrations.AlterField(
            model_name="documentomodelo",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Descrição / Instruções"),
        ),
        migrations.AlterField(
            model_name="documentomodelo",
            name="texto_data_original",
            field=models.CharField(
                help_text='Texto exato que aparece no PDF base e será substituído. Ex: "Salvador - BA, 20 de janeiro de 2026"',
                max_length=300,
                verbose_name="Texto da data no PDF base",
            ),
        ),
        migrations.AlterField(
            model_name="documentomodelo",
            name="tipo",
            field=models.CharField(
                choices=[
                    (
                        "declaracao_simples",
                        "Declaração de Optante pelo Simples Nacional",
                    ),
                    ("planilha_custos", "Planilha de Custos"),
                    ("relatorio_atividades", "Relatório de Atividades"),
                ],
                max_length=40,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="documentomodelogerado",
            name="mes",
            field=models.PositiveSmallIntegerField(verbose_name="Mês"),
        ),
        migrations.AlterField(
            model_name="documentomodelogerado",
            name="texto_data_novo",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Texto da data substituído"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentomodelogerado",
            unique_together={("modelo", "contrato", "mes", "ano")},
        ),
        migrations.RemoveField(
            model_name="documentomodelo",
            name="ativo",
        ),
        migrations.RemoveField(
            model_name="documentomodelo",
            name="contrato",
        ),
        migrations.RemoveField(
            model_name="documentomodelo",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="documentomodelo",
            name="nome_personalizado",
        ),
    ]
