# Generated by Django 5.2.7 on 2026-03-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0042_alter_documentomodelo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentopadrao",
            options={
                "ordering": ["tipo"],
                "verbose_name": "Documento Padrao",
                "verbose_name_plural": "Documentos Padrao",
            },
        ),
        migrations.AddField(
            model_name="documentomodelo",
            name="texto_mes_original",
            field=models.CharField(
                blank=True,
                help_text='Texto exato do mes na capa. Ex: "JANEIRO". Deixe em branco para outros tipos.',
                max_length=100,
                verbose_name="Texto do mes na capa (Relatorio de Atividades)",
            ),
        ),
        migrations.AlterField(
            model_name="documentopadrao",
            name="observacao",
            field=models.TextField(blank=True, verbose_name="Observacao"),
        ),
        migrations.AlterField(
            model_name="documentopadrao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("fgts", "Certidao de Regularidade do FGTS"),
                    ("estadual", "Certidao Negativa Estadual"),
                    ("federal", "Certidao Negativa Federal"),
                    ("municipal", "Certidao Negativa Municipal"),
                    ("trabalhista", "Certidao Negativa Trabalhista"),
                    ("simples", "Comprovacao do Simples Nacional"),
                ],
                max_length=30,
                unique=True,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="enviomensal",
            name="enviado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ultimo envio em"
            ),
        ),
        migrations.AlterField(
            model_name="enviomensal",
            name="mes",
            field=models.PositiveSmallIntegerField(verbose_name="Mes"),
        ),
        migrations.AlterField(
            model_name="enviomensal",
            name="observacao",
            field=models.TextField(blank=True, verbose_name="Observacao"),
        ),
    ]
