# Generated by Django 5.2.7 on 2026-03-16 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0043_alter_documentopadrao_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracaonivel",
            options={
                "verbose_name": "Configuração de Nível",
                "verbose_name_plural": "Configurações de Nível",
            },
        ),
        migrations.AlterModelOptions(
            name="notificacaopush",
            options={"ordering": ["-criado_em"]},
        ),
        migrations.RenameField(
            model_name="notificacaopush",
            old_name="data_criacao",
            new_name="criado_em",
        ),
        migrations.RemoveField(
            model_name="notificacaopush",
            name="data_envio",
        ),
        migrations.AddField(
            model_name="etapa",
            name="modulo",
            field=models.CharField(
                blank=True,
                choices=[("CONTABIL", "Contábil"), ("FINANCEIRO", "Financeiro")],
                default="",
                help_text="Preencher apenas para etapas do nível FECHAMENTO. CONTABIL libera SIGA/SIOPE/SIOPS/SICONF para iniciar. FINANCEIRO libera E-TCM para iniciar.",
                max_length=20,
                verbose_name="Módulo (somente FECHAMENTO)",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaonivel",
            name="clientes_liberados",
            field=models.ManyToManyField(
                blank=True,
                related_name="niveis_liberados",
                to="despesas.cliente",
                verbose_name="Clientes com liberação específica",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaonivel",
            name="liberar_preenchimento",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="etapa",
            name="exige_anexo",
            field=models.BooleanField(
                default=False,
                help_text="O usuário deve anexar um arquivo para concluir esta etapa.",
                verbose_name="Exige Anexo (PDF/Img)",
            ),
        ),
        migrations.AlterField(
            model_name="notificacaopush",
            name="link",
            field=models.CharField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notificacaopush",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="notificacaopush",
            name="usuario_alvo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notificacoes_push",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoreabertura",
            name="solicitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitacoes_reabertura",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CompetenciaLiberada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveIntegerField()),
                ("mes", models.PositiveIntegerField()),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("FECHAMENTO", "FECHAMENTO"),
                            ("SIGA", "SIGA"),
                            ("SIOPS", "SIOPS"),
                            ("SIOPE", "SIOPE"),
                            ("SICONF", "SICONFI"),
                            ("E-TCM", "E-TCM"),
                        ],
                        max_length=30,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("motivo", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencias_liberadas_set",
                        to="despesas.cliente",
                    ),
                ),
                (
                    "liberado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competencias_liberadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Competência Liberada",
                "verbose_name_plural": "Competências Liberadas",
                "ordering": ["-ano", "-mes"],
                "unique_together": {("cliente", "ano", "mes", "nivel")},
            },
        ),
    ]
