# Generated by Django 5.2.7 on 2026-03-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0045_set_modulo_etapas_fechamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMunicipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "municipio",
                    models.CharField(max_length=120, verbose_name="Município"),
                ),
                (
                    "tipo_entidade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("municipio", "Prefeitura"),
                            ("camara", "Câmara Municipal"),
                        ],
                        help_text="Deixe em branco para aplicar a Prefeitura E Câmara do município.",
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de Entidade",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "nome_contato",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Nome do Contato"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False, verbose_name="Marcar como principal"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "E-mail por Município",
                "verbose_name_plural": "E-mails por Município",
                "ordering": ["municipio", "tipo_entidade", "email"],
                "unique_together": {("municipio", "tipo_entidade", "email")},
            },
        ),
    ]
