# Generated by Django 5.2.7 on 2026-05-11 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0046_emailmunicipio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarioperfil",
            name="acesso_prestacao_contas",
            field=models.BooleanField(
                default=False, verbose_name="Acesso Prestação de Contas"
            ),
        ),
        migrations.AddField(
            model_name="usuarioperfil",
            name="perfil_pc",
            field=models.CharField(
                blank=True,
                choices=[("JURIDICO", "Jurídico"), ("ANALISE", "Análise")],
                max_length=20,
                null=True,
                verbose_name="Perfil no módulo PC",
            ),
        ),
        migrations.CreateModel(
            name="PrestacaoContas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_unidade_pdf",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Unidade (PDF)"
                    ),
                ),
                ("competencia_mes", models.PositiveIntegerField(verbose_name="Mês")),
                ("competencia_ano", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "numero_processo",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nº Processo TCM"
                    ),
                ),
                (
                    "inspetoria",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Inspetoria"
                    ),
                ),
                (
                    "etapa_atual",
                    models.CharField(
                        choices=[
                            ("CADASTRO", "Cadastro"),
                            ("ANALISE", "Análise"),
                            ("SIGA", "Correção SIGA"),
                            ("ENVIO_FINAL", "Envio Final"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        db_index=True,
                        default="CADASTRO",
                        max_length=30,
                        verbose_name="Etapa atual",
                    ),
                ),
                (
                    "documento_principal",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="prestacao_contas/documentos/%Y/%m/",
                        verbose_name="Documento Principal (PDF)",
                    ),
                ),
                (
                    "comprovante_envio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="prestacao_contas/comprovantes/%Y/%m/",
                        verbose_name="Comprovante de Envio",
                    ),
                ),
                (
                    "observacao_cadastro",
                    models.TextField(blank=True, verbose_name="Obs. Cadastro"),
                ),
                (
                    "observacao_analise",
                    models.TextField(blank=True, verbose_name="Obs. Análise"),
                ),
                (
                    "observacao_siga",
                    models.TextField(blank=True, verbose_name="Obs. SIGA"),
                ),
                (
                    "observacao_envio",
                    models.TextField(blank=True, verbose_name="Obs. Envio"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now=True)),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pc_cadastradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prestacoes_contas",
                        to="despesas.cliente",
                    ),
                ),
                (
                    "ultimo_editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pc_editadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestação de Contas",
                "verbose_name_plural": "Prestações de Contas",
                "ordering": ["-modificado_em"],
            },
        ),
        migrations.CreateModel(
            name="PCItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Numeração"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "nivel_hierarquico",
                    models.PositiveIntegerField(default=1, verbose_name="Nível"),
                ),
                (
                    "tem_inconsistencia",
                    models.BooleanField(
                        default=False, verbose_name="Tem inconsistência"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(
                        blank=True, verbose_name="Observação de inconsistência"
                    ),
                ),
                ("apontado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "apontado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pc_inconsistencias_apontadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prestacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="despesas.prestacaocontas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Prestação de Contas",
                "verbose_name_plural": "Itens de Prestação de Contas",
                "ordering": ["numero", "id"],
            },
        ),
        migrations.CreateModel(
            name="PCHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etapa_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CADASTRO", "Cadastro"),
                            ("ANALISE", "Análise"),
                            ("SIGA", "Correção SIGA"),
                            ("ENVIO_FINAL", "Envio Final"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "etapa_nova",
                    models.CharField(
                        choices=[
                            ("CADASTRO", "Cadastro"),
                            ("ANALISE", "Análise"),
                            ("SIGA", "Correção SIGA"),
                            ("ENVIO_FINAL", "Envio Final"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        max_length=30,
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prestacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="despesas.prestacaocontas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de PC",
                "verbose_name_plural": "Históricos de PC",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="PCAnexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("CADASTRO", "Cadastro"),
                            ("ANALISE", "Análise"),
                            ("SIGA", "Correção SIGA"),
                            ("ENVIO_FINAL", "Envio Final"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        max_length=30,
                        verbose_name="Etapa",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(upload_to="prestacao_contas/anexos/%Y/%m/"),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descrição"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prestacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="despesas.prestacaocontas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo de PC",
                "verbose_name_plural": "Anexos de PC",
                "ordering": ["-criado_em"],
            },
        ),
    ]
