# Generated by Django 5.2.7 on 2026-05-12 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0047_usuarioperfil_acesso_prestacao_contas_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DespesaGeral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classificacao",
                    models.CharField(
                        choices=[
                            ("aluguel", "Aluguel"),
                            ("gastos_diversos", "Gastos Diversos"),
                            ("alimentacao", "Alimentação"),
                            ("transporte", "Transporte"),
                            ("consignado", "Consignado"),
                            ("financiamentos", "Financiamentos"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Classificação",
                    ),
                ),
                (
                    "classificacao_custom",
                    models.CharField(
                        blank=True,
                        help_text='Preenchido apenas quando classificação = "outros"',
                        max_length=100,
                        null=True,
                        verbose_name="Classificação Personalizada",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Usado no transporte em lote (valor × qtd_colaboradores)",
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Unitário",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Para transporte: quantidade de colaboradores",
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Se transporte: calculado automaticamente como unitário × qtd",
                        max_digits=12,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "mes_referencia",
                    models.DateField(
                        help_text="Sempre o 1º dia do mês de referência (ex: 2025-01-01)",
                        verbose_name="Mês de Referência",
                    ),
                ),
                (
                    "recorrente",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, replica nos meses seguintes",
                        verbose_name="Recorrente",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("pago", "Pago")],
                        default="pendente",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="despesas_gerais_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa Geral",
                "verbose_name_plural": "Despesas Gerais",
                "ordering": ["mes_referencia", "classificacao", "descricao"],
            },
        ),
    ]
