# Generated by Django 5.2.7 on 2026-05-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0048_despesageral"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesageral",
            name="data_vencimento",
            field=models.DateField(
                blank=True,
                help_text="Data limite de pagamento. Gera alertas conforme lembretes.",
                null=True,
                verbose_name="Data de Vencimento",
            ),
        ),
        migrations.AddField(
            model_name="despesageral",
            name="lembrete_antecedencia",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ex: [7, 3, 1, 0] — notifica 7d, 3d, 1d antes e no dia.",
                verbose_name="Lembretes (dias antes)",
            ),
        ),
        migrations.AlterField(
            model_name="despesageral",
            name="classificacao",
            field=models.CharField(
                choices=[
                    ("aluguel", "Aluguel"),
                    ("gastos_diversos", "Gastos Diversos"),
                    ("alimentacao", "Alimentação"),
                    ("transporte", "Transporte"),
                    ("consignado", "Consignado"),
                    ("financiamentos", "Financiamentos"),
                    ("outros", "Outros"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="despesageral",
            name="classificacao_custom",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="despesageral",
            name="descricao",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="despesageral",
            name="mes_referencia",
            field=models.DateField(
                help_text="Sempre o 1º dia do mês de referência (ex: 2025-01-01)"
            ),
        ),
        migrations.AlterField(
            model_name="despesageral",
            name="observacao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="despesageral",
            name="quantidade",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="despesageral",
            name="recorrente",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="despesageral",
            name="status",
            field=models.CharField(
                choices=[("pendente", "Pendente"), ("pago", "Pago")],
                default="pendente",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="despesageral",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="despesageral",
            name="valor_unitario",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
