# Generated by Django 5.2.7 on 2026-05-12 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0049_despesageral_data_vencimento_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pcitem",
            name="confirmado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pcitem",
            name="confirmado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pc_itens_confirmados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pcitem",
            name="status_siga",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("INCONSISTENTE", "Inconsistente"),
                    ("OK_ANALISE", "OK (Análise/Jurídico)"),
                    ("CONFIRMADO_SIGA", "Confirmado pelo SIGA"),
                    ("DEVOLVIDO", "Devolvido para revisão"),
                ],
                default="PENDENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="despesageral",
            name="data_vencimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="despesageral",
            name="lembrete_antecedencia",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="despesageral",
            name="mes_referencia",
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name="PCItemAnotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INCONSISTENCIA", "Inconsistência"),
                            ("OK", "OK"),
                            ("OBSERVACAO", "Observação"),
                            ("CONFIRMACAO", "Confirmação SIGA"),
                            ("DEVOLUCAO", "Devolução SIGA"),
                        ],
                        default="OBSERVACAO",
                        max_length=20,
                    ),
                ),
                ("texto", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anotacoes",
                        to="despesas.pcitem",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pc_anotacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anotação de Item PC",
                "verbose_name_plural": "Anotações de Itens PC",
                "ordering": ["criado_em"],
            },
        ),
        migrations.CreateModel(
            name="PCPrazo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                ("data_limite", models.DateField(verbose_name="Data Limite")),
                (
                    "dias_lembrete",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Quantos dias antes do vencimento enviar o lembrete push.",
                        verbose_name="Lembrete (dias antes)",
                    ),
                ),
                (
                    "concluido",
                    models.BooleanField(default=False, verbose_name="Concluído"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("lembrete_enviado", models.BooleanField(default=False)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pc_prazos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prestacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prazos",
                        to="despesas.prestacaocontas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prazo de PC",
                "verbose_name_plural": "Prazos de PC",
                "ordering": ["data_limite"],
            },
        ),
        migrations.CreateModel(
            name="PCRetorno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.TextField(verbose_name="Motivo do retorno")),
                ("etapa_origem", models.CharField(default="SIGA", max_length=30)),
                ("etapa_destino", models.CharField(default="ANALISE", max_length=30)),
                ("processado", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "prestacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retornos",
                        to="despesas.prestacaocontas",
                    ),
                ),
                (
                    "solicitado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pc_retornos_solicitados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Retorno de Etapa PC",
                "verbose_name_plural": "Retornos de Etapa PC",
                "ordering": ["-criado_em"],
            },
        ),
    ]
