# Generated by Django 5.2.7 on 2026-05-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0050_pcitem_confirmado_em_pcitem_confirmado_por_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacaocontas",
            name="periodo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1Q", "1º Quadrimestre"),
                    ("2Q", "2º Quadrimestre"),
                    ("3Q", "3º Quadrimestre"),
                    ("ANUAL", "Anual"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
