# Generated by Django 5.2.7 on 2026-05-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0051_prestacaocontas_periodo"),
    ]

    operations = [
        migrations.CreateModel(
            name="VinculoCentroCustoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_automaticamente", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "centro_de_custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_contrato",
                        to="despesas.centrodecusto",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_centro_custo",
                        to="despesas.contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo Centro de Custo x Contrato",
                "verbose_name_plural": "Vínculos Centros de Custo x Contratos",
                "unique_together": {("centro_de_custo", "contrato")},
            },
        ),
    ]
