# Generated by Django 5.2.7 on 2026-05-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0052_vinculocentrocustocontrato"),
    ]

    operations = [
        migrations.AddField(
            model_name="vinculocentrocustocontrato",
            name="tipo_entidade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PM", "Prefeitura"),
                    ("CM", "Câmara Municipal"),
                    ("AUT", "Autarquia"),
                ],
                max_length=3,
                null=True,
                verbose_name="Tipo de Entidade",
            ),
        ),
    ]
