# Generated by Django 5.2.7 on 2026-05-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0053_vinculocentrocustocontrato_tipo_entidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despesageral",
            name="classificacao",
            field=models.CharField(
                choices=[
                    ("aluguel", "Aluguel"),
                    ("gastos_diversos", "Gastos Diversos"),
                    ("alimentacao", "Alimentação"),
                    ("transporte", "Transporte"),
                    ("consignado", "Consignado"),
                    ("financiamentos", "Financiamentos"),
                    ("energia", "Energia"),
                    ("outros", "Outros"),
                ],
                max_length=20,
            ),
        ),
    ]
