# Generated by Django 5.2.7 on 2026-05-25 18:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0054_alter_despesageral_classificacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentual_imposto_nota",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Percentual de imposto aplicado sobre o valor da nota fiscal na análise detalhada por município. Ex.: 2.00 para 2%.",
                        max_digits=5,
                        verbose_name="% Imposto sobre Nota Fiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração Financeira",
                "verbose_name_plural": "Configurações Financeiras",
            },
        ),
        migrations.AddField(
            model_name="despesageral",
            name="municipio",
            field=models.CharField(
                blank=True,
                help_text="Associe esta despesa a um município para que ela apareça na análise detalhada por município (Raio X → Por Município).",
                max_length=120,
                null=True,
                verbose_name="Município",
            ),
        ),
        migrations.CreateModel(
            name="VinculoFuncionarioCentro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_funcionario",
                        to="despesas.centrodecusto",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_centro",
                        to="despesas.usuarioperfil",
                        verbose_name="Funcionário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo Funcionário × Centro de Custo",
                "verbose_name_plural": "Vínculos Funcionários × Centros de Custo",
                "ordering": [
                    "perfil__user__first_name",
                    "perfil__user__last_name",
                    "centro",
                ],
                "unique_together": {("perfil", "centro")},
            },
        ),
    ]
