# Generated by Django 5.2.7 on 2026-05-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0055_configuracaofinanceira_despesageral_municipio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesageral",
            name="recorrencia_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="UUID compartilhado entre todas as cópias da mesma despesa recorrente.",
                null=True,
                verbose_name="ID de Recorrência",
            ),
        ),
    ]
