# Generated by Django 5.2.7 on 2026-05-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0056_despesageral_recorrencia_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesageral",
            name="tipo_orgao",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Tipo Órgão"
            ),
        ),
    ]
