# Generated by Django 5.2.7 on 2026-06-01 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0057_despesageral_tipo_orgao"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcanexo",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anexos",
                to="despesas.pcitem",
            ),
        ),
    ]
