# Generated by Django 5.2.7 on 2026-07-14 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0058_pcanexo_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrevisaoPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("municipio", models.CharField(max_length=150)),
                (
                    "tipo_entidade",
                    models.CharField(
                        choices=[
                            ("municipio", "Prefeitura Municipal"),
                            ("camara", "Câmara Municipal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("competencia_mes", models.PositiveSmallIntegerField()),
                ("competencia_ano", models.PositiveSmallIntegerField()),
                (
                    "data_prevista",
                    models.DateField(verbose_name="Data prevista de pagamento"),
                ),
                (
                    "valor_previsto",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Aguardando"),
                            ("cumprida", "Cumprida"),
                            ("nao_cumprida", "Não cumprida"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "data_verificacao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data em que foi marcada cumprida/não cumprida",
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previsoes_atualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previsoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Previsão de Pagamento",
                "verbose_name_plural": "Previsões de Pagamento",
                "ordering": ["-competencia_ano", "-competencia_mes", "municipio"],
            },
        ),
        migrations.CreateModel(
            name="PrevisaoPagamentoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("criada", "Previsão criada"),
                            ("editada", "Previsão editada"),
                            ("cumprida", "Marcada como cumprida"),
                            ("nao_cumprida", "Marcada como não cumprida"),
                            ("reaberta", "Reaberta (voltou a pendente)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_prevista_snapshot", models.DateField(blank=True, null=True)),
                (
                    "valor_previsto_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "previsao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="despesas.previsaopagamento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Previsão",
                "verbose_name_plural": "Histórico de Previsões",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddConstraint(
            model_name="previsaopagamento",
            constraint=models.UniqueConstraint(
                fields=(
                    "municipio",
                    "tipo_entidade",
                    "competencia_mes",
                    "competencia_ano",
                ),
                name="uniq_previsao_municipio_entidade_competencia",
            ),
        ),
    ]
