# Generated by Django 5.2.7 on 2026-08-10 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despesas", "0059_previsaopagamento_previsaopagamentolog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoteContracheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo_original",
                    models.FileField(
                        upload_to="contracheques/lotes/%Y/%m/",
                        verbose_name="PDF Original do Lote",
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Mês de Referência (informado)",
                    ),
                ),
                (
                    "ano",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Ano de Referência (informado)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSANDO", "Processando"),
                            ("AGUARDANDO_CONFIRMACAO", "Aguardando Confirmação do RH"),
                            ("CONCLUIDO", "Concluído"),
                            ("ERRO", "Erro no Processamento"),
                        ],
                        default="PROCESSANDO",
                        max_length=30,
                    ),
                ),
                ("total_paginas", models.PositiveIntegerField(default=0)),
                ("paginas_processadas", models.PositiveIntegerField(default=0)),
                ("log_erro", models.TextField(blank=True, verbose_name="Log de Erro")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lotes_contracheque_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de Contracheques",
                "verbose_name_plural": "Lotes de Contracheques",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Contracheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.PositiveSmallIntegerField(verbose_name="Mês")),
                ("ano", models.PositiveSmallIntegerField(verbose_name="Ano")),
                (
                    "numero_pagina",
                    models.PositiveIntegerField(verbose_name="Página no PDF original"),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="contracheques/recibos/%Y/%m/",
                        verbose_name="PDF do Contracheque",
                    ),
                ),
                (
                    "nome_extraido",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="Nome extraído (OCR)"
                    ),
                ),
                (
                    "cargo_extraido",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="Cargo extraído (OCR)"
                    ),
                ),
                (
                    "codigo_funcionario",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Código do Funcionário (folha)",
                    ),
                ),
                (
                    "valor_bruto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total de Vencimentos",
                    ),
                ),
                (
                    "valor_descontos",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total de Descontos",
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Líquido",
                    ),
                ),
                (
                    "score_match",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Confiança do Match (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Aguardando Confirmação"),
                            ("CONFIRMADO", "Confirmado"),
                            ("SEM_CORRESPONDENCIA", "Sem Correspondência"),
                        ],
                        default="PENDENTE",
                        max_length=25,
                    ),
                ),
                ("confirmado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracheques_confirmados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracheques",
                        to="despesas.usuarioperfil",
                        verbose_name="Colaborador (confirmado)",
                    ),
                ),
                (
                    "perfil_sugerido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracheques_sugeridos",
                        to="despesas.usuarioperfil",
                        verbose_name="Colaborador (sugestão automática)",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracheques",
                        to="despesas.lotecontracheque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contracheque",
                "verbose_name_plural": "Contracheques",
                "ordering": ["-ano", "-mes", "perfil__user__first_name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("perfil__isnull", False)),
                        fields=("perfil", "mes", "ano"),
                        name="uniq_contracheque_perfil_mes_ano",
                    )
                ],
            },
        ),
    ]
