# Generated by Django 5.2.7 on 2026-08-18 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0060_lotecontracheque_contracheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSaatri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=60, verbose_name='Método SOAP')),
                ('url', models.URLField(verbose_name='URL Endpoint')),
                ('xml_envio', models.TextField(verbose_name='XML Enviado')),
                ('xml_retorno', models.TextField(blank=True, verbose_name='XML Retornado')),
                ('http_status', models.IntegerField(null=True, verbose_name='HTTP Status')),
                ('sucesso', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('erro', models.TextField(blank=True, verbose_name='Erro')),
                ('duracao_ms', models.IntegerField(null=True, verbose_name='Duração (ms)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log SAATRI',
                'verbose_name_plural': 'Logs SAATRI',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SaatriNumeracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proximo_numero_rps', models.PositiveIntegerField(default=3260)),
            ],
            options={
                'verbose_name': 'Numeração RPS SAATRI',
                'verbose_name_plural': 'Numeração RPS SAATRI',
            },
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='codigo_verificacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Verificação SAATRI'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='origem',
            field=models.CharField(choices=[('omie', 'Omie'), ('saatri', 'SAATRI Direto')], default='omie', help_text="'omie' = faturada/emitida pela Omie (fluxo padrão). 'saatri' = emitida direto no Web Service SAATRI, sem passar pela Omie.", max_length=10, verbose_name='Origem da Emissão'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='xml_completo',
            field=models.TextField(blank=True, null=True, verbose_name='XML Completo (SAATRI)'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='omie_nfse_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID NFS-e Omie'),
        ),
        migrations.CreateModel(
            name='RpsSaatri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número do RPS')),
                ('serie', models.CharField(default='9000', max_length=5, verbose_name='Série')),
                ('tipo', models.CharField(default='1', max_length=1, verbose_name='Tipo')),
                ('competencia_mes', models.PositiveSmallIntegerField()),
                ('competencia_ano', models.PositiveSmallIntegerField()),
                ('valor_servicos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aliquota', models.DecimalField(decimal_places=10, default=0, max_digits=14)),
                ('valor_iss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discriminacao', models.TextField()),
                ('item_lista_servico', models.CharField(max_length=8)),
                ('codigo_nbs', models.CharField(blank=True, max_length=9)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado (aguardando SEFIN)'), ('convertido', 'Convertido em NFS-e'), ('erro', 'Erro')], default='rascunho', max_length=12)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rps_saatri_list', to='despesas.contrato', verbose_name='Contrato')),
                ('nota_fiscal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rps_saatri', to='despesas.notafiscal')),
            ],
            options={
                'verbose_name': 'RPS SAATRI',
                'verbose_name_plural': 'RPS SAATRI',
                'ordering': ['-criado_em'],
                'unique_together': {('numero', 'serie', 'tipo')},
            },
        ),
    ]
