# Generated by Django 5.2.7 on 2026-08-18 21:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0061_logsaatri_saatrinumeracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='aliquota_iss',
            field=models.DecimalField(decimal_places=10, default=Decimal('2.00'), max_digits=14, verbose_name='Alíquota ISS % (cache local)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='codigo_nbs',
            field=models.CharField(blank=True, default='113022100', max_length=9, verbose_name='Código NBS (cache local)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='dados_locais_atualizados_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cache local atualizado em'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='dados_tomador',
            field=models.JSONField(blank=True, default=dict, help_text="Cópia local do cadastro fiscal do cliente na Omie (CNPJ/CPF, endereço, município IBGE, telefone, e-mail) — mesmo formato usado pelo emissor SAATRI. Só é atualizado quando 'Sincronizar com Omie' está ligado (é sempre lido da Omie, nunca editado manualmente).", verbose_name='Dados Fiscais do Tomador (cache local)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='descricao_servico',
            field=models.TextField(blank=True, default='', help_text="Cópia local da descrição usada na nota. Atualizada junto com a Omie quando 'Sincronizar com Omie' está ligado, ou só localmente quando desligado.", verbose_name='Descrição do Serviço (cache local)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='item_lista_servico',
            field=models.CharField(blank=True, default='17.19.01', max_length=8, verbose_name='Item Lista Serviço (cache local)'),
        ),
    ]
