# Generated by Django 5.2.7 on 2026-08-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0062_contrato_aliquota_iss_contrato_codigo_nbs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_mostra_status_faturamento', models.BooleanField(default=False, help_text="Filtro de mês/ano + coluna 'Faturado/Não faturado' na lista de contratos em /receitas/. Desligado por padrão — o indicador oficial de notas já faturadas/pendentes fica no fluxo de 'Faturar em lote' (ver painel de confirmação do modal de edição em lote).", verbose_name='Mostrar status de faturamento por competência no dashboard de contratos')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
