# Generated by Django 5.2.7 on 2026-08-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0063_configuracaosistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='origem',
            field=models.CharField(choices=[('omie', 'Omie'), ('saatri', 'SAATRI Direto'), ('manual', 'Importada Manualmente')], default='omie', help_text="'omie' = faturada/emitida pela Omie (fluxo padrão). 'saatri' = emitida direto no Web Service SAATRI, sem passar pela Omie. 'manual' = nota já existente cadastrada à mão (ex.: emitida fora do sistema).", max_length=10, verbose_name='Origem da Emissão'),
        ),
    ]
