# Generated by Django 5.2.7 on 2026-08-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0064_alter_notafiscal_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='cnpj_tomador',
            field=models.CharField(blank=True, help_text="Preenchido nas notas importadas manualmente (essencial nas 'avulsas', sem Contrato associado) — permite localizar por CNPJ na Consulta de Notas.", max_length=20, null=True, verbose_name='CNPJ/CPF do Tomador (cache)'),
        ),
    ]
